# Generated by Django 5.2.7 on 2025-10-13 06:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeterBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_cubic', models.DecimalField(decimal_places=2, default=Decimal('22.50'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], max_length=10)),
                ('spouse_name', models.CharField(blank=True, max_length=50, null=True)),
                ('household_number', models.CharField(max_length=20)),
                ('usage_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=20)),
                ('serial_number', models.CharField(max_length=50)),
                ('first_reading', models.IntegerField()),
                ('registration_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Connected'), ('disconnected', 'Disconnected')], default='active', help_text='Connected or Disconnected consumer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.barangay')),
                ('meter_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.meterbrand')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('reading_value', models.IntegerField()),
                ('source', models.CharField(default='manual', max_length=50)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='consumers.consumer')),
            ],
            options={
                'ordering': ['-reading_date'],
                'unique_together': {('consumer', 'reading_date')},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.DateField(help_text='First day of the billing month (e.g., 2025-10-01)')),
                ('due_date', models.DateField()),
                ('consumption', models.PositiveIntegerField(help_text='in cubic meters')),
                ('rate_per_cubic', models.DecimalField(decimal_places=2, default=Decimal('22.50'), max_digits=6)),
                ('fixed_charge', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='consumers.consumer')),
                ('current_reading', models.ForeignKey(help_text='The latest meter reading used for this bill', on_delete=django.db.models.deletion.PROTECT, related_name='bills_as_current', to='consumers.meterreading')),
                ('previous_reading', models.ForeignKey(blank=True, help_text='The meter reading from the previous billing cycle', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills_as_previous', to='consumers.meterreading')),
            ],
            options={
                'verbose_name': 'Utility Bill',
                'verbose_name_plural': 'Utility Bills',
                'ordering': ['-billing_period'],
            },
        ),
        migrations.CreateModel(
            name='Purok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puroks', to='consumers.barangay')),
            ],
        ),
        migrations.AddField(
            model_name='consumer',
            name='purok',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.purok'),
        ),
    ]
