# Generated by Django 5.2.7 on 2025-10-14 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_consumer_account_number_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, help_text='Actual amount due from the bill', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(help_text='The bill being paid', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='consumers.bill'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Change to return to the consumer', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='or_number',
            field=models.CharField(editable=False, help_text='Official Receipt number (auto-generated)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, help_text='Cash amount received from the consumer', max_digits=10),
        ),
    ]
