# Generated by Django 5.2.7 on 2025-10-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0004_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='barangay_id_number',
            field=models.CharField(blank=True, help_text='Automatically generated ID based on barangay (e.g., CBW-0001)', max_length=20, unique=True),
        ),
    ]
