# Generated by Django 5.2.7 on 2025-10-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0005_consumer_barangay_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='barangay_id_number',
        ),
    ]
