# Generated by Django 5.2.7 on 2025-10-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0006_remove_consumer_barangay_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='disconnect_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
