# Generated by Django 5.2.7 on 2025-11-05 14:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0007_consumer_disconnect_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the user logged in.')),
                ('user', models.ForeignKey(help_text='The user who logged in.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_timestamp'],
            },
        ),
    ]
