# Generated by Django 5.2.7 on 2025-11-06 14:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0008_userloginevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsetting',
            name='rate_per_cubic',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='commercial_rate_per_cubic',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Rate applied to commercial consumers (₱ / m³)', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='residential_rate_per_cubic',
            field=models.DecimalField(decimal_places=2, default=Decimal('22.50'), help_text='Rate applied to residential consumers (₱ / m³)', max_digits=10),
        ),
    ]
