# Generated by Django 5.2.7 on 2025-11-11 13:32

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0009_remove_systemsetting_rate_per_cubic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userloginevent',
            options={'ordering': ['-login_timestamp'], 'verbose_name': 'User Login Event', 'verbose_name_plural': 'User Login Events'},
        ),
        migrations.AddField(
            model_name='userloginevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the login attempt', null=True),
        ),
        migrations.AddField(
            model_name='userloginevent',
            name='login_method',
            field=models.CharField(choices=[('web', 'Web Portal'), ('mobile', 'Mobile App'), ('api', 'API')], default='web', help_text='Method used to login', max_length=20),
        ),
        migrations.AddField(
            model_name='userloginevent',
            name='logout_timestamp',
            field=models.DateTimeField(blank=True, help_text='When the user logged out', null=True),
        ),
        migrations.AddField(
            model_name='userloginevent',
            name='session_key',
            field=models.CharField(blank=True, help_text='Django session key', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userloginevent',
            name='status',
            field=models.CharField(choices=[('success', 'Successful'), ('failed', 'Failed'), ('locked', 'Account Locked')], default='success', help_text='Login attempt status', max_length=20),
        ),
        migrations.AddField(
            model_name='userloginevent',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser/device information'),
        ),
        migrations.AlterField(
            model_name='userloginevent',
            name='login_timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='The date and time the user logged in.'),
        ),
        migrations.AddIndex(
            model_name='userloginevent',
            index=models.Index(fields=['login_timestamp'], name='consumers_u_login_t_cf1769_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginevent',
            index=models.Index(fields=['user', 'login_timestamp'], name='consumers_u_user_id_91ec72_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginevent',
            index=models.Index(fields=['status'], name='consumers_u_status_8444e1_idx'),
        ),
    ]
