# Generated by Django 5.2.7 on 2025-11-13 12:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0010_add_security_fields_to_login_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='billing_day_of_month',
            field=models.IntegerField(default=1, help_text='Day of month for billing period (1-28)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='due_day_of_month',
            field=models.IntegerField(default=20, help_text='Day of month for bill due date (1-28)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='fixed_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Fixed charge added to every bill (₱)', max_digits=10),
        ),
    ]
