# Generated by Django 5.2.7 on 2025-11-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0012_passwordresettoken_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo for admin users', null=True, upload_to='profile_photos/'),
        ),
    ]
