# Generated by Django 5.2.7 on 2025-11-21 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0013_staffprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='assigned_barangay',
            field=models.ForeignKey(blank=True, help_text='Required for field staff only', null=True, on_delete=django.db.models.deletion.CASCADE, to='consumers.barangay'),
        ),
    ]
