# Generated by Django 5.2.7 on 2025-11-22 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0014_alter_staffprofile_assigned_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='login_event',
            field=models.ForeignKey(blank=True, help_text='The login session during which this activity occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='consumers.userloginevent'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed'), ('password_changed', 'Password Changed'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('bill_created', 'Bill Created'), ('payment_processed', 'Payment Processed'), ('meter_reading_confirmed', 'Meter Reading Confirmed'), ('meter_reading_submitted', 'Meter Reading Submitted'), ('consumer_disconnected', 'Consumer Disconnected'), ('consumer_reconnected', 'Consumer Reconnected')], max_length=50),
        ),
    ]
