# Generated by Django 5.2.7 on 2025-11-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0015_useractivity_login_event_alter_useractivity_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed'), ('password_changed', 'Password Changed'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('bill_created', 'Bill Created'), ('payment_processed', 'Payment Processed'), ('meter_reading_confirmed', 'Meter Reading Confirmed'), ('meter_reading_submitted', 'Meter Reading Submitted'), ('consumer_created', 'Consumer Created'), ('consumer_updated', 'Consumer Updated'), ('consumer_disconnected', 'Consumer Disconnected'), ('consumer_reconnected', 'Consumer Reconnected'), ('system_settings_updated', 'System Settings Updated')], max_length=50),
        ),
    ]
