# Generated by Django 5.2.7 on 2025-11-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0016_alter_useractivity_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meterreading',
            options={'ordering': ['-reading_date', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='meterreading',
            unique_together=set(),
        ),
    ]
