# Generated by Django 5.2.7 on 2025-11-23 04:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0017_remove_unique_together_meter_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='reading_end_day',
            field=models.IntegerField(default=10, help_text='Day of month when reading period ends (1-28)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='reading_start_day',
            field=models.IntegerField(default=1, help_text='Day of month when reading period starts (1-28)'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='billing_day_of_month',
            field=models.IntegerField(default=1, help_text='Day shown as billing period start on bills (1-28)'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='commercial_rate_per_cubic',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Rate for commercial consumers (₱ / m³)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='due_day_of_month',
            field=models.IntegerField(default=20, help_text='Day when payment is due (1-28)'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='residential_rate_per_cubic',
            field=models.DecimalField(decimal_places=2, default=Decimal('22.50'), help_text='Rate for residential consumers (₱ / m³)', max_digits=10),
        ),
    ]
