# Generated by Django 5.2.7 on 2025-11-24 10:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0018_add_reading_schedule_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='days_overdue',
            field=models.IntegerField(default=0, help_text='Number of days the bill is/was overdue'),
        ),
        migrations.AddField(
            model_name='bill',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated penalty amount for late payment', max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='penalty_applied_date',
            field=models.DateField(blank=True, help_text='Date when penalty was first applied', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='penalty_waived',
            field=models.BooleanField(default=False, help_text='Whether the penalty has been waived by admin'),
        ),
        migrations.AddField(
            model_name='bill',
            name='penalty_waived_by',
            field=models.ForeignKey(blank=True, help_text='Admin who waived the penalty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='penalty_waived_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when penalty was waived', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='penalty_waived_reason',
            field=models.CharField(blank=True, help_text='Reason for waiving the penalty', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='days_overdue_at_payment',
            field=models.IntegerField(default=0, help_text='Number of days overdue at the time of payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_bill_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original bill amount before penalty', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Penalty amount included in this payment', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='penalty_waived',
            field=models.BooleanField(default=False, help_text='Whether penalty was waived for this payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Staff who processed the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional notes or remarks about the payment'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='fixed_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text="Fixed penalty amount in pesos (used if penalty_type is 'fixed')", max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='max_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Maximum penalty cap (0 = no cap)', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='penalty_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable late payment penalties'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='penalty_grace_period_days',
            field=models.IntegerField(default=0, help_text='Number of days after due date before penalty is applied (0 = immediate)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Penalty rate in percentage (e.g., 10 for 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='penalty_type',
            field=models.CharField(choices=[('percentage', 'Percentage of Bill'), ('fixed', 'Fixed Amount')], default='percentage', help_text='Type of penalty calculation', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, help_text='Total amount paid (bill + penalty)', max_digits=10),
        ),
    ]
