# Generated by Django 5.2.7 on 2025-11-24 23:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0019_add_penalty_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('meter_reading', 'Meter Reading Submitted'), ('payment', 'Payment Processed'), ('bill_generated', 'Bill Generated'), ('consumer_registered', 'New Consumer Registered'), ('system_alert', 'System Alert')], help_text='Type of notification', max_length=30)),
                ('title', models.CharField(help_text='Short notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of related object (e.g., MeterReading ID)', null=True)),
                ('redirect_url', models.CharField(blank=True, help_text='URL to redirect when clicked', max_length=500)),
                ('is_read', models.BooleanField(default=False, help_text='Has the user read this notification?')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, help_text='When was it marked as read', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Specific user to notify (null = all admins)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='consumers_n_user_id_080238_idx'), models.Index(fields=['is_read', '-created_at'], name='consumers_n_is_read_0dd5fa_idx'), models.Index(fields=['notification_type', '-created_at'], name='consumers_n_notific_434fdd_idx')],
            },
        ),
    ]
