# Generated by Django 5.2.7 on 2025-11-25 15:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0020_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='commercial_minimum_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Minimum charge for 1-5 m³ consumption (₱)', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='commercial_tier2_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Rate for 6-10 m³ consumption (₱/m³)', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='commercial_tier3_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Rate for 11-20 m³ consumption (₱/m³)', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='commercial_tier4_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('22.00'), help_text='Rate for 21-50 m³ consumption (₱/m³)', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='commercial_tier5_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('24.00'), help_text='Rate for 51+ m³ consumption (₱/m³)', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='residential_minimum_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('75.00'), help_text='Minimum charge for 1-5 m³ consumption (₱)', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='residential_tier2_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Rate for 6-10 m³ consumption (₱/m³)', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='residential_tier3_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Rate for 11-20 m³ consumption (₱/m³)', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='residential_tier4_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('17.00'), help_text='Rate for 21-50 m³ consumption (₱/m³)', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='residential_tier5_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Rate for 51+ m³ consumption (₱/m³)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='commercial_rate_per_cubic',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='[LEGACY] Rate for commercial consumers (₱ / m³)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='fixed_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='[LEGACY] Fixed charge - no longer used with tiered rates', max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='residential_rate_per_cubic',
            field=models.DecimalField(decimal_places=2, default=Decimal('22.50'), help_text='[LEGACY] Rate for residential consumers (₱ / m³)', max_digits=10),
        ),
    ]
