# Generated by Django 5.2.7 on 2025-11-25 15:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0021_add_tiered_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='max_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum penalty cap (0 = no cap, penalty is full percentage of bill)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='penalty_grace_period_days',
            field=models.IntegerField(default=0, help_text='Number of days after due date before penalty is applied (0 = immediate, penalty starts day after due date)'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Penalty rate in percentage (default: 25% of bill amount)', max_digits=5),
        ),
    ]
