# Generated by Django 5.2.7 on 2025-11-27 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0023_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField()),
                ('reason', models.CharField(default='Too many failed login attempts', max_length=255)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Is this lockout still in effect?')),
            ],
            options={
                'verbose_name': 'Account Lockout',
                'verbose_name_plural': 'Account Lockouts',
                'ordering': ['-locked_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttemptTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('attempt_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('was_successful', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(help_text='Base32 encoded secret key', max_length=32)),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Has the user verified their 2FA setup?')),
                ('backup_codes', models.TextField(blank=True, help_text='JSON list of backup codes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Two-Factor Authentication',
                'verbose_name_plural': 'Two-Factor Authentications',
            },
        ),
        migrations.AlterModelOptions(
            name='consumer',
            options={'ordering': ['-created_at'], 'permissions': [('view_consumer_data', 'Can view consumer data (read-only)'), ('edit_consumer_data', 'Can edit consumer information'), ('create_consumer_account', 'Can create new consumers'), ('remove_consumer', 'Can delete/remove consumers'), ('disconnect_consumer', 'Can disconnect/reconnect consumers'), ('manage_billing', 'Can manage billing (create bills, process payments)'), ('view_billing', 'Can view billing records'), ('generate_reports', 'Can generate and download reports'), ('view_reports', 'Can view reports'), ('manage_users', 'Can manage user accounts'), ('manage_settings', 'Can access system settings')]},
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='bill_consumer_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='bill_due_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='bill_status_due_idx',
        ),
        migrations.RemoveIndex(
            model_name='consumer',
            name='consumer_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='consumer',
            name='consumer_brgy_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='meterreading',
            name='reading_consumer_conf_idx',
        ),
        migrations.RemoveIndex(
            model_name='meterreading',
            name='reading_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='meterreading',
            name='reading_latest_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_bill_idx',
        ),
        migrations.AddField(
            model_name='accountlockout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginattempttracker',
            index=models.Index(fields=['ip_address', 'attempt_time'], name='consumers_l_ip_addr_8db4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempttracker',
            index=models.Index(fields=['username', 'attempt_time'], name='consumers_l_usernam_84a675_idx'),
        ),
        migrations.AddField(
            model_name='twofactorauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accountlockout',
            index=models.Index(fields=['username', 'is_active'], name='consumers_a_usernam_b4c7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='accountlockout',
            index=models.Index(fields=['ip_address', 'is_active'], name='consumers_a_ip_addr_aa4b49_idx'),
        ),
    ]
