# Generated by Django 5.2.7 on 2025-11-28 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0024_add_security_models_and_fix_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='assigned_barangay',
            field=models.ForeignKey(blank=True, help_text='Required for Field Staff only', null=True, on_delete=django.db.models.deletion.CASCADE, to='consumers.barangay'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('cashier', 'Cashier'), ('field_staff', 'Field Staff')], default='field_staff', help_text='User role determines dashboard access and permissions', max_length=20),
        ),
    ]
