# Generated by Django 5.2.7 on 2025-11-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0025_staffprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
