# Generated by Django 5.2.7 on 2025-11-29
# Data migration to assign ID numbers to all existing consumers

from django.db import migrations
from datetime import datetime
import re


def assign_id_numbers(apps, schema_editor):
    """
    Assign ID numbers (YYYYMMXXXX format) to all consumers without one.
    This runs automatically during migration on deployment.
    """
    Consumer = apps.get_model('consumers', 'Consumer')

    # Get all consumers without ID numbers (NULL or empty)
    consumers_without_id = Consumer.objects.filter(
        id_number__isnull=True
    ).order_by('created_at') | Consumer.objects.filter(
        id_number=''
    ).order_by('created_at')

    if not consumers_without_id.exists():
        print("All consumers already have ID numbers.")
        return

    print(f"Found {consumers_without_id.count()} consumers without ID numbers.")

    # Get current year-month prefix
    now = datetime.now()
    year_month_prefix = now.strftime('%Y%m')  # e.g., '202511'

    # Find all existing ID numbers to avoid duplicates
    all_existing_ids = set(
        Consumer.objects.exclude(id_number__isnull=True)
        .exclude(id_number='')
        .values_list('id_number', flat=True)
    )

    # Find the highest sequential number for this month
    max_seq = 0
    pattern = f'^{year_month_prefix}(\\d{{4}})$'
    for id_num in all_existing_ids:
        if id_num:
            match = re.match(pattern, str(id_num))
            if match:
                seq = int(match.group(1))
                if seq > max_seq:
                    max_seq = seq

    # Assign ID numbers to consumers without one
    updated_count = 0
    current_seq = max_seq + 1

    for consumer in consumers_without_id:
        # Generate unique ID number
        while True:
            new_id = f'{year_month_prefix}{current_seq:04d}'
            if new_id not in all_existing_ids:
                consumer.id_number = new_id
                consumer.save(update_fields=['id_number'])
                all_existing_ids.add(new_id)
                updated_count += 1
                print(f"  Assigned {new_id} to {consumer.first_name} {consumer.last_name}")
                current_seq += 1
                break
            current_seq += 1
            if current_seq > 9999:
                raise ValueError(f"ID number limit reached for {year_month_prefix}")

    print(f"Successfully assigned ID numbers to {updated_count} consumers.")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - do nothing (we don't want to remove ID numbers)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0026_add_id_number_field'),
    ]

    operations = [
        migrations.RunPython(assign_id_numbers, reverse_migration),
    ]
