# Generated by Django 5.2.7 on 2025-11-29 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0027_assign_id_numbers_to_existing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When was it archived', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived after 30 days'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_archived', '-created_at'], name='consumers_n_is_arch_c1e2db_idx'),
        ),
    ]
