# Generated by Django 5.2.7 on 2025-11-29 01:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0028_add_notification_archive_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_user_id', models.IntegerField(help_text='Original User ID before deletion')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('was_staff', models.BooleanField(default=False)),
                ('was_superuser', models.BooleanField(default=False)),
                ('was_active', models.BooleanField(default=True)),
                ('staff_role', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned_barangay_name', models.CharField(blank=True, max_length=100, null=True)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archive_reason', models.CharField(blank=True, default='User deleted by admin', max_length=255)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, help_text='Admin who archived this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived User',
                'verbose_name_plural': 'Archived Users',
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['username'], name='consumers_a_usernam_27e1d2_idx'), models.Index(fields=['archived_at'], name='consumers_a_archive_185730_idx')],
            },
        ),
    ]
