# Generated by Django 5.2.7 on 2025-11-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0030_update_admin_to_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='suffix',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Jr.', 'Jr.'), ('Sr.', 'Sr.'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('cashier', 'Cashier'), ('field_staff', 'Field Staff')], default='field_staff', help_text='User role determines dashboard access and permissions', max_length=20),
        ),
    ]
