# Generated by Django 5.2.7 on 2025-11-30 15:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0031_add_consumer_suffix_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'verbose_name': 'System Setting', 'verbose_name_plural': 'System Settings'},
        ),
        migrations.CreateModel(
            name='SystemSettingChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('change_type', models.CharField(choices=[('reading_schedule', 'Reading Schedule'), ('billing_schedule', 'Billing Schedule'), ('residential_rates', 'Residential Rates'), ('commercial_rates', 'Commercial Rates'), ('penalty_settings', 'Penalty Settings'), ('multiple', 'Multiple Settings')], default='multiple', max_length=30)),
                ('description', models.TextField(help_text='Human-readable description of changes')),
                ('previous_values', models.JSONField(blank=True, default=dict, help_text='Previous settings values (JSON)')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New settings values (JSON)')),
                ('effective_immediately', models.BooleanField(default=True, help_text='All changes take effect immediately')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Settings Change Log',
                'verbose_name_plural': 'Settings Change Logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['-changed_at'], name='consumers_s_changed_f2cd4c_idx'), models.Index(fields=['change_type', '-changed_at'], name='consumers_s_change__97112b_idx')],
            },
        ),
    ]
