# Generated by Django 5.2.7 on 2025-11-30 17:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0032_add_system_setting_change_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tier1_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum charge amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='tier1_consumption',
            field=models.PositiveIntegerField(default=0, help_text='Units in Tier 1 (1-5 m³)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tier2_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='tier2_consumption',
            field=models.PositiveIntegerField(default=0, help_text='Units in Tier 2 (6-10 m³)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tier2_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate per m³ for Tier 2', max_digits=6),
        ),
        migrations.AddField(
            model_name='bill',
            name='tier3_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='tier3_consumption',
            field=models.PositiveIntegerField(default=0, help_text='Units in Tier 3 (11-20 m³)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tier3_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate per m³ for Tier 3', max_digits=6),
        ),
        migrations.AddField(
            model_name='bill',
            name='tier4_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='tier4_consumption',
            field=models.PositiveIntegerField(default=0, help_text='Units in Tier 4 (21-50 m³)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tier4_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate per m³ for Tier 4', max_digits=6),
        ),
        migrations.AddField(
            model_name='bill',
            name='tier5_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='tier5_consumption',
            field=models.PositiveIntegerField(default=0, help_text='Units in Tier 5 (51+ m³)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tier5_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate per m³ for Tier 5', max_digits=6),
        ),
        migrations.AlterField(
            model_name='bill',
            name='fixed_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deprecated - use tier1_amount for minimum charge', max_digits=8),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rate_per_cubic',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average rate (for display only)', max_digits=6),
        ),
    ]
