# Generated by Django 5.2.7 on 2025-11-30 22:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0033_add_tiered_rate_fields_to_bill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who confirmed this reading', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Was this reading rejected?'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='proof_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL of meter photo proof', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='Admin who rejected this reading', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='rejection_reason',
            field=models.CharField(blank=True, help_text='Reason for rejection (required when rejecting)', max_length=255),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Field staff who submitted this reading', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Has admin confirmed this reading?'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='reading_value',
            field=models.IntegerField(help_text='Cumulative meter value'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='source',
            field=models.CharField(choices=[('manual', 'Office Manual Entry'), ('mobile_app', 'Mobile App (OCR)'), ('manual_with_proof', 'Manual with Proof Photo'), ('smart_meter', 'Smart Meter')], default='manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='commercial_tier5_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Rate for 51+ m³ consumption (₱/m³)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='residential_tier5_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Rate for 51+ m³ consumption (₱/m³)', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['is_confirmed', 'is_rejected'], name='reading_status_idx'),
        ),
    ]
