# Generated by Django 5.2.7 on 2026-01-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0038_assign_id_numbers_to_existing_consumers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('meter_reading', 'Meter Reading Submitted'), ('reading_pending_confirmation', 'Reading Pending Confirmation'), ('payment', 'Payment Processed'), ('bill_generated', 'Bill Generated'), ('consumer_registered', 'New Consumer Registered'), ('system_alert', 'System Alert')], help_text='Type of notification', max_length=30),
        ),
        migrations.DeleteModel(
            name='ArchivedUser',
        ),
    ]
