# Generated by Django 5.2.7 on 2026-01-13 01:40

from django.db import migrations


def update_source_types(apps, schema_editor):
    """
    Update MeterReading source values from old to new types:
    - 'mobile_app' → 'app_scanned' (OCR scan, auto-confirmed)
    - 'manual_with_proof' → 'app_manual' (manual entry with proof photo)
    - 'smart_meter' → 'app_scanned' (IoT device readings)
    - 'manual' → remains 'manual' (office manual entry)
    """
    MeterReading = apps.get_model('consumers', 'MeterReading')

    # Update mobile_app to app_scanned
    updated_mobile = MeterReading.objects.filter(source='mobile_app').update(source='app_scanned')

    # Update manual_with_proof to app_manual
    updated_manual_proof = MeterReading.objects.filter(source='manual_with_proof').update(source='app_manual')

    # Update smart_meter to app_scanned
    updated_smart = MeterReading.objects.filter(source='smart_meter').update(source='app_scanned')

    print(f"Migration complete:")
    print(f"  - Updated {updated_mobile} 'mobile_app' records to 'app_scanned'")
    print(f"  - Updated {updated_manual_proof} 'manual_with_proof' records to 'app_manual'")
    print(f"  - Updated {updated_smart} 'smart_meter' records to 'app_scanned'")


def reverse_update_source_types(apps, schema_editor):
    """
    Reverse migration - restore old source values.
    Note: This may not be 100% accurate since smart_meter and mobile_app both map to app_scanned.
    """
    MeterReading = apps.get_model('consumers', 'MeterReading')

    # Reverse app_manual to manual_with_proof
    MeterReading.objects.filter(source='app_manual').update(source='manual_with_proof')

    # Reverse app_scanned to mobile_app (best guess)
    MeterReading.objects.filter(source='app_scanned').update(source='mobile_app')


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0039_remove_archived_user'),
    ]

    operations = [
        migrations.RunPython(update_source_types, reverse_update_source_types),
    ]
