# Generated by Django 5.2.7 on 2026-02-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0040_update_meter_reading_source_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='source',
            field=models.CharField(choices=[('app_scanned', 'App - OCR Scan'), ('app_manual', 'App - Manual Entry'), ('manual', 'Office Manual Entry')], default='manual', max_length=50),
        ),
    ]
