# Generated by Django 5.2.7 on 2026-02-11 02:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0041_alter_meterreading_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='senior_citizen_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='5% discount on penalty for senior citizens', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='senior_citizen_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Senior citizen discount applied on penalty', max_digits=10),
        ),
    ]
