# Generated by Django 5.2.7 on 2026-02-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0042_bill_senior_citizen_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('cashier', 'Cashier'), ('field_staff', 'Field Staff')], default='field_staff', help_text='User role determines dashboard access and permissions', max_length=20),
        ),
    ]
