# Generated by Django 5.2.7 on 2026-02-25 02:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0043_add_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='senior_citizen_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='5% discount on water bill for senior citizens with consumption ≤ 30 m³', max_digits=10),
        ),
    ]
