# Generated by Django 5.2.7 on 2026-03-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0044_alter_bill_senior_citizen_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='queued_for_payment',
            field=models.BooleanField(default=False, help_text='True if Inquire office selected this for payment'),
        ),
    ]
